server:
  port: 8761
spring:
  application:
    name: REGISTRY-SERVICE  
    
eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 30    expected-client-renewal-interval-seconds: 10
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    # service-url:
    # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka