server:
  port: 8001
    
spring:
  profiles:    active:    - pear1
  application:
    name: REGISTRY-SERVICE-pear1
    
eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 30
    renewal-percent-threshold: 0.85 
  instance:
    hostname: pear1
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://pear2:8002/eureka,http://pear3:8003/eureka
           