server:
  port: 8002
    
spring:
  profiles:    active:    - pear2
  application:
    name: REGISTRY-SERVICE - pear2
    
eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 30
    renewal-percent-threshold: 0.85 
  instance:
    hostname: pear2
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://pear1:8001/eureka,http://pear3:8003/eureka
             