server:
  port: 9999

spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dharm117x/config-server.git
          username: 
          password: 
          clone-on-start:  true