server:
  port: 9000

spring:  application:    name: DEPARTMENT-SERVICE  
  cloud:
    config:
      enabled: true    
  config:
    import:
    - optional:configserver:http://localhost:9999 
    
  