server:
  port: 8000
  
spring:
  application:
    name: USER-SERVICE
  cloud:    config:      enabled: true    
  config:    import:    - optional:configserver:http://localhost:9999 

eureka:  client:    service-url:
     # defaultZone: http://pear1:8001/eureka, http://pear2:8002/eureka, http://pear3:8003/eureka
      defaultZone: http://localhost:8761/eureka
            
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      dept-service:
        requestInterceptors:
        - com.dksite.FeignRequestInterceptor
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full


                    
management:  endpoints:    web:      exposure:        include:        - "*"

resilience4j:  circuitbreaker:    instances:      DEPARTMENTSERVICE:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based  
        