server:
  port: 8000
  
spring:
  application:
    name: USER-SERVICE
  cloud:    config:      enabled: true    
  config:    import:    - optional:configserver:http://localhost:9999 

management:  endpoints:    web:      exposure:        include:        - "*"

resilience4j:  circuitbreaker:    instances:      DEPARTMENTSERVICE:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based  
        